import {
  IconCoffee,
  IconSoup,
  IconToolsKitchen2,
  IconBread,
  IconCup,
  IconGlassFull,
  IconScissors,
  IconBarbell,
  IconSchool,
  IconStethoscope,
  IconShoppingBag,
  IconBuildingCottage,
  IconPackage,
  IconGift,
  IconTag,
  IconKey,
  IconLayoutDashboard,
  IconUsers,
  IconSettings,
  IconAdjustments,
  IconPlugConnected,
  IconRocket,
  IconSearch,
  IconBrandAmazon,
  IconFileInvoice,
  IconInfoCircle,
  IconCircleCheck,
} from "@tabler/icons-react";
import type { TablerIcon } from "@/types/listing";

/** Maps source-HTML `ti-*` icon class names to their Tabler React equivalent. */
const map: Record<string, TablerIcon> = {
  "ti-coffee": IconCoffee,
  "ti-soup": IconSoup,
  "ti-tools-kitchen-2": IconToolsKitchen2,
  "ti-bread": IconBread,
  "ti-cup": IconCup,
  "ti-glass-full": IconGlassFull,
  "ti-scissors": IconScissors,
  "ti-barbell": IconBarbell,
  "ti-school": IconSchool,
  "ti-stethoscope": IconStethoscope,
  "ti-shopping-bag": IconShoppingBag,
  "ti-building-cottage": IconBuildingCottage,
  "ti-package": IconPackage,
  "ti-gift": IconGift,
  "ti-tag": IconTag,
  "ti-key": IconKey,
  "ti-layout-dashboard": IconLayoutDashboard,
  "ti-users": IconUsers,
  "ti-settings": IconSettings,
  "ti-adjustments": IconAdjustments,
  "ti-plug-connected": IconPlugConnected,
  "ti-rocket": IconRocket,
  "ti-search": IconSearch,
  "ti-brand-amazon": IconBrandAmazon,
  "ti-file-invoice": IconFileInvoice,
  "ti-info-circle": IconInfoCircle,
  "ti-circle-check": IconCircleCheck,
};

export function iconFor(name: string): TablerIcon {
  return map[name] ?? IconTag;
}
